fix(build): Fix Local Build Conflicts with `math_functions.h`
Attempts to fix:
```
mathcalls.h(79): error: exception specification is incompatible with
that of previous function "cospi" (declared at line 5554 of
targets/x86_64-linux/include/crt/math_functions.h)
```